// Cards Actions
export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const FETCH_CARDS = 'FETCH_CARDS';
export const GET_CARD = 'GET_CARD';
export const IMPORT_CARDS = 'IMPORT_CARDS';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILED = 'CARD_CREATE_FAILED';
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS';
export const CARD_DELETE_FAILED = 'CARD_DELETE_FAILED';
export const CARD_EDIT_SUCCESS = 'CARD_EDIT_SUCCESS';
export const CARD_EDIT_FAILED = 'CARD_EDIT_FAILED';
export const CARD_FETCHED_SUCCESS = 'CARD_FETCHED_SUCCESS';
export const CARD_FETCHED_FAILED = 'CARD_FETCHED_FAILED';
export const CARDS_FETCHED_SUCCESS = 'CARDS_FETCHED_SUCCESS';
export const CARDS_FETCHED_FAILED = 'CARDS_FETCHED_FAILED';
export const CARDS_IMPORT_SUCCESS = 'CARDS_IMPORT_SUCCESS';
export const CARDS_IMPORT_FAILED = 'CARDS_IMPORT_FAILED';
// Notificatiosn
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';