// Cards Actions
export const ADD_CARD = 'ADD_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const FETCH_CARDS = 'FETCH_CARDS';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILED = 'CARD_CREATE_FAILED';
export const CARD_EDIT_SUCCESS = 'CARD_EDIT_SUCCESS';
export const CARD_EDIT_FAILED = 'CARD_EDIT_FAILED';
export const CARDS_FETCHED_SUCCESS = 'CARDS_FETCHED_SUCCESS';
export const CARDS_FETCHED_FAILED = 'CARDS_FETCHED_FAILED';